<a href="https://colab.research.google.com/github/harkie24/genlink/blob/main/GenLink.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **GenLink**
Connecting Rare Diseases to the Genome

In [6]:
import pandas as pd

**Loading the Datasets**

In [7]:
genes = pd.read_csv("/content/ensembl_genes.csv")
diseases = pd.read_csv("/content/rare_gene_disease_dataset.csv")

**Exploring the Data**

In [53]:
print("Ensembl Dataset Shape:", genes.shape)
print("Diseases Dataset Shape:", diseases.shape)

Ensembl Dataset Shape: (78691, 8)
Diseases Dataset Shape: (8374, 3)

In [10]:
genes.head()

,ensembl_gene_id,gene_symbol,chromosome,start,end,strand,biotype,description
0,ENSG00000210049,MT-TF,MT,577,647,1,Mt_tRNA,mitochondrially encoded tRNA-Phe (UUU/C) [Sour...
1,ENSG00000211459,MT-RNR1,MT,648,1601,1,Mt_rRNA,mitochondrially encoded 12S rRNA [Source:HGNC ...
2,ENSG00000210077,MT-TV,MT,1602,1670,1,Mt_tRNA,mitochondrially encoded tRNA-Val (GUN) [Source...
3,ENSG00000210082,MT-RNR2,MT,1671,3229,1,Mt_rRNA,mitochondrially encoded 16S rRNA [Source:HGNC ...
4,ENSG00000209082,MT-TL1,MT,3230,3304,1,Mt_tRNA,mitochondrially encoded tRNA-Leu (UUA/G) 1 [So...

In [11]:
diseases.head()

,disease,gene_symbol,gene_full_name
0,Multiple epiphyseal dysplasia-macrocephaly-fac...,KIF7,kinesin family member 7
1,Brachydactyly-short stature-retinitis pigmento...,CWC27,CWC27 spliceosome associated cyclophilin
2,Aspartylglucosaminuria,AGA,aspartylglucosaminidase
3,Multiple sulfatase deficiency,SUMF1,sulfatase modifying factor 1
4,Beta-mannosidosis,MANBA,mannosidase beta

In [12]:
print(genes.columns)
print(diseases.columns)

Index(['ensembl_gene_id', 'gene_symbol', 'chromosome', 'start', 'end',
       'strand', 'biotype', 'description'],
      dtype='object')
Index(['disease', 'gene_symbol', 'gene_full_name'], dtype='object')

**Missing Value Analysis**

In [13]:
genes_null_count = genes.isnull().sum()
diseases_null_count = diseases.isnull().sum()

print("Genes Dataset Null Count:\n", genes_null_count)
print("\nDiseases Dataset Null Count:\n", diseases_null_count)

Genes Dataset Null Count:
 ensembl_gene_id        0
gene_symbol        35661
chromosome             0
start                  0
end                    0
strand                 0
biotype                0
description          642
dtype: int64

Diseases Dataset Null Count:
 disease           0
gene_symbol       0
gene_full_name    0
dtype: int64

**Statistics**

In [17]:
print(f"Unique Diseases: {diseases['disease'].nunique()}")

Unique Diseases: 4128

In [21]:
print(f"Unique Genes: {diseases['gene_symbol'].nunique()}")

Unique Genes: 4552

**Disease Search Tool**

In [22]:
disease_name = input("Enter disease name: ")

result = diseases[diseases['disease'].str.contains(disease_name, case = False)]
print(result)

Enter disease name: gluco
                                                disease gene_symbol  \
2                                Aspartylglucosaminuria         AGA
2196  Juvenile cataract-microcornea-renal glucosuria...    SLC16A12
3075  Hemolytic anemia due to glucophosphate isomera...         GPI
3158                    Adult polyglucosan body disease        GBE1
3423                 Familial glucocorticoid deficiency        STAR
3424                 Familial glucocorticoid deficiency        MC2R
3425                 Familial glucocorticoid deficiency        MRAP
3426                 Familial glucocorticoid deficiency      TXNRD2
3427                 Familial glucocorticoid deficiency         NNT
4600                  Polyglucosan body myopathy type 2        GYG1
4661  Class I glucose-6-phosphate dehydrogenase defi...        G6PD
4820                  Polyglucosan body myopathy type 1       RBCK1
5405     Generalized glucocorticoid resistance syndrome       NR3C1
5554  Classic glucose transporter type 1 deficiency ...      SLC2A1
5585                          Familial renal glucosuria      SLC5A2
5858                    Glucose-galactose malabsorption      SLC5A1
6739  Glycogen storage disease due to glucose-6-phos...     SLC37A4
6740  Glycogen storage disease due to glucose-6-phos...       G6PC1
6749     Congenital glucokinase-related hyperinsulinism         GCK

                                         gene_full_name
2                               aspartylglucosaminidase
2196                 solute carrier family 16 member 12
3075                      glucose-6-phosphate isomerase
3158                1,4-alpha-glucan branching enzyme 1
3423             steroidogenic acute regulatory protein
3424                            melanocortin 2 receptor
3425          melanocortin 2 receptor accessory protein
3426                            thioredoxin reductase 2
3427           nicotinamide nucleotide transhydrogenase
4600                                       glycogenin 1
4661                  glucose-6-phosphate dehydrogenase
4820  RANBP2-type and C3HC4-type zinc finger contain...
5405      nuclear receptor subfamily 3 group C member 1
5554                   solute carrier family 2 member 1
5585                   solute carrier family 5 member 2
5858                   solute carrier family 5 member 1
6739                  solute carrier family 37 member 4
6740          glucose-6-phosphatase catalytic subunit 1
6749                                        glucokinase

**Gene Search Tool**

In [26]:
gene_name = input("Enter gene name: ")

result = diseases[diseases['gene_symbol'].str.contains(gene_name, case=False)]

print(result)

Enter gene name: kt
                                                disease gene_symbol  \
389                                     Cowden syndrome        AKT1
799                                    Proteus syndrome        AKT1
868            Familial isolated dilated cardiomyopathy        FKTN
1651                                         Meningioma        AKT1
3007  Non-syndromic male infertility due to sperm mo...       TEKT3
3077  Fukutin-related limb-girdle muscular dystrophy...        FKTN
4067  Congenital muscular dystrophy without intellec...        FKTN
4224  Hypoinsulinemic hypoglycemia and body hemihype...        AKT2
5231                           Muscle-eye-brain disease        FKTN
5240                            Walker-Warburg syndrome        FKTN
5251       Congenital muscular dystrophy, Fukuyama type        FKTN
5519                           Transketolase deficiency         TKT
5754        AKT2-related familial partial lipodystrophy        AKT2
6917  Megalencephaly-polymicrogyria-postaxial polyda...        AKT3
8263                                 Hemimegalencephaly        AKT3

                     gene_full_name
389   AKT serine/threonine kinase 1
799   AKT serine/threonine kinase 1
868                         fukutin
1651  AKT serine/threonine kinase 1
3007                       tektin 3
3077                        fukutin
4067                        fukutin
4224  AKT serine/threonine kinase 2
5231                        fukutin
5240                        fukutin
5251                        fukutin
5519                  transketolase
5754  AKT serine/threonine kinase 2
6917  AKT serine/threonine kinase 3
8263  AKT serine/threonine kinase 3

**Top 20 Most Frequent Genes**

---

.value_counts() counts how many times each gene appears.

In [29]:
top20_genes = (diseases['gene_symbol'].value_counts().head(20))
top20_genes

gene_symbol
HBB         29
TP53        22
LMNA        21
KIT         19
COL2A1      18
FGFR1       17
PIK3CA      15
HLA-DRB1    14
PTEN        14
PAX6        13
BRAF        13
FGFR3       13
SHH         13
TTN         13
BRCA2       12
CTNNB1      12
IDH2        12
FGFR2       12
RYR1        12
KRAS        11
Name: count, dtype: int64

**Top 20 Diseases**

In [30]:
top20_diseases = (diseases['disease'].value_counts().head(20))
top20_diseases

disease
Non-specific syndromic intellectual disability                                      114
Retinitis pigmentosa                                                                 88
Rare autosomal recessive non-syndromic sensorineural deafness type DFNB              74
Autosomal recessive non-syndromic intellectual disability                            54
Non-specific early-onset epileptic encephalopathy                                    54
Familial isolated dilated cardiomyopathy                                             53
Primary ciliary dyskinesia                                                           53
Rare autosomal dominant non-syndromic sensorineural deafness type DFNA               50
Autosomal dominant non-syndromic intellectual disability                             43
Male infertility with azoospermia or oligozoospermia due to single gene mutation     37
Amyotrophic lateral sclerosis                                                        36
Hereditary steroid-resistant nephrotic syndrome                                      34
Cone rod dystrophy                                                                   32
Isolated Joubert syndrome                                                            30
Systemic lupus erythematosus                                                         30
X-linked non-syndromic intellectual disability                                       30
Differentiated thyroid carcinoma                                                     29
Autosomal recessive primary microcephaly                                             29
Isolated complex I deficiency                                                        29
Diamond-Blackfan anemia                                                              26
Name: count, dtype: int64

# **Merging both Datasets**

The 'gene_symbol column is the only common column between the two datasets.

*   *Rare Gene Diseases* dataset gives disease-gene relationship
*   *Ensemble Genes* dataset gives us gene-gene information relationship

So it can be useful to merge these datasets.

In [32]:
merged = pd.merge(diseases, genes, left_on = 'gene_symbol', right_on = 'gene_symbol', how = 'inner')
merged.head()

,disease,gene_symbol,gene_full_name,ensembl_gene_id,chromosome,start,end,strand,biotype,description
0,Multiple epiphyseal dysplasia-macrocephaly-fac...,KIF7,kinesin family member 7,ENSG00000166813,15,89608789,89663098,-1,protein_coding,kinesin family member 7 [Source:HGNC Symbol;Ac...
1,Brachydactyly-short stature-retinitis pigmento...,CWC27,CWC27 spliceosome associated cyclophilin,ENSG00000153015,5,64766368,65102412,1,protein_coding,CWC27 spliceosome associated cyclophilin [Sour...
2,Aspartylglucosaminuria,AGA,aspartylglucosaminidase,ENSG00000038002,4,177430774,177442444,-1,protein_coding,aspartylglucosaminidase [Source:HGNC Symbol;Ac...
3,Multiple sulfatase deficiency,SUMF1,sulfatase modifying factor 1,ENSG00000144455,3,3700814,4467273,-1,protein_coding,sulfatase modifying factor 1 [Source:HGNC Symb...
4,Beta-mannosidosis,MANBA,mannosidase beta,ENSG00000109323,4,102630770,102760999,-1,protein_coding,mannosidase beta [Source:HGNC Symbol;Acc:HGNC:...

**how = "inner"** keeps only the matches

**how = "left"** keeps everything from the disease dataset

**how = "right"** keeps everything from the gene dataset

**how = "outer"** keeps everything from both datasets

**Chromosome Analysis**

In [37]:
chromosome_counts = (merged['chromosome'].value_counts())
chromosome_counts

chromosome
1     773
2     615
11    547
3     523
17    518
X     457
12    433
6     402
19    364
7     360
5     353
10    339
16    330
4     322
9     312
14    281
8     275
15    262
22    197
20    179
13    159
18    133
MT     86
21     83
Y      18
Name: count, dtype: int64

# **Gene Biotype Analysis**

**Top 5 Biotypes**

In [40]:
top5_biotype = (merged['biotype'].value_counts())
top5_biotype

biotype
protein_coding            8229
Mt_tRNA                     36
lncRNA                      28
snRNA                        7
IG_C_gene                    5
miRNA                        4
ribozyme                     3
IG_V_gene                    2
Mt_rRNA                      2
TEC                          2
unprocessed_pseudogene       1
TR_C_gene                    1
snoRNA                       1
Name: count, dtype: int64

In [44]:
biotype_df = (merged['biotype'].value_counts().reset_index())
biotype_df

                   biotype  count
0           protein_coding   8229
1                  Mt_tRNA     36
2                   lncRNA     28
3                    snRNA      7
4                IG_C_gene      5
5                    miRNA      4
6                 ribozyme      3
7                IG_V_gene      2
8                  Mt_rRNA      2
9                      TEC      2
10  unprocessed_pseudogene      1
11               TR_C_gene      1
12                  snoRNA      1

**Calculating Percentages**

In [45]:
biotype_df['Percentage'] = (biotype_df['count']/biotype_df['count'].sum())*100
biotype_df

                   biotype  count  Percentage
0           protein_coding   8229   98.894364
1                  Mt_tRNA     36    0.432640
2                   lncRNA     28    0.336498
3                    snRNA      7    0.084125
4                IG_C_gene      5    0.060089
5                    miRNA      4    0.048071
6                 ribozyme      3    0.036053
7                IG_V_gene      2    0.024036
8                  Mt_rRNA      2    0.024036
9                      TEC      2    0.024036
10  unprocessed_pseudogene      1    0.012018
11               TR_C_gene      1    0.012018
12                  snoRNA      1    0.012018

**Finding the Most Common Biotype**

idxmax() returns the index of the maximum

In [48]:
most_common = (merged['biotype'].value_counts().idxmax())
print("Most common biotype:", most_common)

Most common biotype: protein_coding

**Finding the Least Common Biotype**

In [49]:
least_common = (merged['biotype'].value_counts().idxmin())
print("Least common biotype:", least_common)

Least common biotype: unprocessed_pseudogene

**Filter Only Protein-Coding Genes**

In [51]:
protein_genes = merged[ merged['biotype'] == 'protein_coding']
protein_genes.head()

,disease,gene_symbol,gene_full_name,ensembl_gene_id,chromosome,start,end,strand,biotype,description
0,Multiple epiphyseal dysplasia-macrocephaly-fac...,KIF7,kinesin family member 7,ENSG00000166813,15,89608789,89663098,-1,protein_coding,kinesin family member 7 [Source:HGNC Symbol;Ac...
1,Brachydactyly-short stature-retinitis pigmento...,CWC27,CWC27 spliceosome associated cyclophilin,ENSG00000153015,5,64766368,65102412,1,protein_coding,CWC27 spliceosome associated cyclophilin [Sour...
2,Aspartylglucosaminuria,AGA,aspartylglucosaminidase,ENSG00000038002,4,177430774,177442444,-1,protein_coding,aspartylglucosaminidase [Source:HGNC Symbol;Ac...
3,Multiple sulfatase deficiency,SUMF1,sulfatase modifying factor 1,ENSG00000144455,3,3700814,4467273,-1,protein_coding,sulfatase modifying factor 1 [Source:HGNC Symb...
4,Beta-mannosidosis,MANBA,mannosidase beta,ENSG00000109323,4,102630770,102760999,-1,protein_coding,mannosidase beta [Source:HGNC Symbol;Acc:HGNC:...

**Number of Diseases per Biotype**

In [58]:
disease_per_biotype = (merged.groupby('biotype')['disease'].nunique().sort_values(ascending=False))
disease_per_biotype

biotype
protein_coding            4078
lncRNA                      25
Mt_tRNA                     15
snRNA                        7
IG_C_gene                    4
miRNA                        4
ribozyme                     3
IG_V_gene                    2
Mt_rRNA                      2
TEC                          2
TR_C_gene                    1
snoRNA                       1
unprocessed_pseudogene       1
Name: disease, dtype: int64

**Complete Analysis**

.agg() allows multiple different calculations on different columns at the same time

In [63]:
biotype_analysis = (merged.groupby('biotype').agg(
    Total_Genes = ('gene_symbol', 'nunique'),
    Total_Diseases = ('disease', 'nunique'),
).sort_values(
    by = 'Total_Genes',
    ascending = False
)
)
biotype_analysis

                        Total_Genes  Total_Diseases
biotype
protein_coding                 4457            4078
Mt_tRNA                          15              15
lncRNA                           13              25
IG_C_gene                         4               4
miRNA                             4               4
snRNA                             4               7
IG_V_gene                         2               2
TEC                               2               2
Mt_rRNA                           1               2
TR_C_gene                         1               1
ribozyme                          1               3
snoRNA                            1               1
unprocessed_pseudogene            1               1

**Average Genes per Disease**

In [65]:
avg = (diseases.groupby('disease')['gene_symbol'].nunique().mean())
print("Average Genes per Disease: ", avg)

Average Genes per Disease:  2.020591085271318