<a href="https://colab.research.google.com/github/harkie24/genlink/blob/main/notebooks/01_Data_Loading.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

**Loading the Datasets**

In [4]:
genes = pd.read_csv("/content/ensembl_genes.csv")
diseases = pd.read_csv("/content/rare_gene_disease_dataset.csv")

**Exploring the Data**

In [5]:
print("Ensembl Dataset Shape:", genes.shape)
print("Diseases Dataset Shape:", diseases.shape)

Ensembl Dataset Shape: (78691, 8)
Diseases Dataset Shape: (8374, 3)

In [6]:
genes.head()

,ensembl_gene_id,gene_symbol,chromosome,start,end,strand,biotype,description
0,ENSG00000210049,MT-TF,MT,577,647,1,Mt_tRNA,mitochondrially encoded tRNA-Phe (UUU/C) [Sour...
1,ENSG00000211459,MT-RNR1,MT,648,1601,1,Mt_rRNA,mitochondrially encoded 12S rRNA [Source:HGNC ...
2,ENSG00000210077,MT-TV,MT,1602,1670,1,Mt_tRNA,mitochondrially encoded tRNA-Val (GUN) [Source...
3,ENSG00000210082,MT-RNR2,MT,1671,3229,1,Mt_rRNA,mitochondrially encoded 16S rRNA [Source:HGNC ...
4,ENSG00000209082,MT-TL1,MT,3230,3304,1,Mt_tRNA,mitochondrially encoded tRNA-Leu (UUA/G) 1 [So...

In [7]:
diseases.head()

,disease,gene_symbol,gene_full_name
0,Multiple epiphyseal dysplasia-macrocephaly-fac...,KIF7,kinesin family member 7
1,Brachydactyly-short stature-retinitis pigmento...,CWC27,CWC27 spliceosome associated cyclophilin
2,Aspartylglucosaminuria,AGA,aspartylglucosaminidase
3,Multiple sulfatase deficiency,SUMF1,sulfatase modifying factor 1
4,Beta-mannosidosis,MANBA,mannosidase beta

In [8]:
print(genes.columns)
print(diseases.columns)

Index(['ensembl_gene_id', 'gene_symbol', 'chromosome', 'start', 'end',
       'strand', 'biotype', 'description'],
      dtype='object')
Index(['disease', 'gene_symbol', 'gene_full_name'], dtype='object')