<a href="https://colab.research.google.com/github/harkie24/genlink/blob/main/notebooks/02_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
genes = pd.read_csv("/content/ensembl_genes.csv")
diseases = pd.read_csv("/content/rare_gene_disease_dataset.csv")

**Missing Value Analysis**

In [4]:
genes_null_count = genes.isnull().sum()
diseases_null_count = diseases.isnull().sum()

print("Genes Dataset Null Count:\n", genes_null_count)
print("\nDiseases Dataset Null Count:\n", diseases_null_count)

Genes Dataset Null Count:
 ensembl_gene_id        0
gene_symbol        35661
chromosome             0
start                  0
end                    0
strand                 0
biotype                0
description          642
dtype: int64

Diseases Dataset Null Count:
 disease           0
gene_symbol       0
gene_full_name    0
dtype: int64

**Statistics**

In [5]:
print(f"Unique Diseases: {diseases['disease'].nunique()}")

Unique Diseases: 4128

**Disease Search Tool**

In [6]:
disease_name = input("Enter disease name: ")

result = diseases[diseases['disease'].str.contains(disease_name, case = False)]
print(result)

Enter disease name: gluco
                                                disease gene_symbol  \
2                                Aspartylglucosaminuria         AGA
2196  Juvenile cataract-microcornea-renal glucosuria...    SLC16A12
3075  Hemolytic anemia due to glucophosphate isomera...         GPI
3158                    Adult polyglucosan body disease        GBE1
3423                 Familial glucocorticoid deficiency        STAR
3424                 Familial glucocorticoid deficiency        MC2R
3425                 Familial glucocorticoid deficiency        MRAP
3426                 Familial glucocorticoid deficiency      TXNRD2
3427                 Familial glucocorticoid deficiency         NNT
4600                  Polyglucosan body myopathy type 2        GYG1
4661  Class I glucose-6-phosphate dehydrogenase defi...        G6PD
4820                  Polyglucosan body myopathy type 1       RBCK1
5405     Generalized glucocorticoid resistance syndrome       NR3C1
5554  Classic glucose transporter type 1 deficiency ...      SLC2A1
5585                          Familial renal glucosuria      SLC5A2
5858                    Glucose-galactose malabsorption      SLC5A1
6739  Glycogen storage disease due to glucose-6-phos...     SLC37A4
6740  Glycogen storage disease due to glucose-6-phos...       G6PC1
6749     Congenital glucokinase-related hyperinsulinism         GCK

                                         gene_full_name
2                               aspartylglucosaminidase
2196                 solute carrier family 16 member 12
3075                      glucose-6-phosphate isomerase
3158                1,4-alpha-glucan branching enzyme 1
3423             steroidogenic acute regulatory protein
3424                            melanocortin 2 receptor
3425          melanocortin 2 receptor accessory protein
3426                            thioredoxin reductase 2
3427           nicotinamide nucleotide transhydrogenase
4600                                       glycogenin 1
4661                  glucose-6-phosphate dehydrogenase
4820  RANBP2-type and C3HC4-type zinc finger contain...
5405      nuclear receptor subfamily 3 group C member 1
5554                   solute carrier family 2 member 1
5585                   solute carrier family 5 member 2
5858                   solute carrier family 5 member 1
6739                  solute carrier family 37 member 4
6740          glucose-6-phosphatase catalytic subunit 1
6749                                        glucokinase

**Gene Search Tool**

In [ ]:
gene_name = input("Enter gene name: ")

result = diseases[diseases['gene_symbol'].str.contains(gene_name, case=False)]

print(result)

**Top 20 Most Frequent Genes**

---

.value_counts() counts how many times each gene appears.

In [7]:
top20_genes = (diseases['gene_symbol'].value_counts().head(20))
top20_genes

gene_symbol
HBB         29
TP53        22
LMNA        21
KIT         19
COL2A1      18
FGFR1       17
PIK3CA      15
HLA-DRB1    14
PTEN        14
PAX6        13
BRAF        13
FGFR3       13
SHH         13
TTN         13
BRCA2       12
CTNNB1      12
IDH2        12
FGFR2       12
RYR1        12
KRAS        11
Name: count, dtype: int64

**Top 20 Diseases**

In [8]:
top20_diseases = (diseases['disease'].value_counts().head(20))
top20_diseases

disease
Non-specific syndromic intellectual disability                                      114
Retinitis pigmentosa                                                                 88
Rare autosomal recessive non-syndromic sensorineural deafness type DFNB              74
Autosomal recessive non-syndromic intellectual disability                            54
Non-specific early-onset epileptic encephalopathy                                    54
Familial isolated dilated cardiomyopathy                                             53
Primary ciliary dyskinesia                                                           53
Rare autosomal dominant non-syndromic sensorineural deafness type DFNA               50
Autosomal dominant non-syndromic intellectual disability                             43
Male infertility with azoospermia or oligozoospermia due to single gene mutation     37
Amyotrophic lateral sclerosis                                                        36
Hereditary steroid-resistant nephrotic syndrome                                      34
Cone rod dystrophy                                                                   32
Isolated Joubert syndrome                                                            30
Systemic lupus erythematosus                                                         30
X-linked non-syndromic intellectual disability                                       30
Differentiated thyroid carcinoma                                                     29
Autosomal recessive primary microcephaly                                             29
Isolated complex I deficiency                                                        29
Diamond-Blackfan anemia                                                              26
Name: count, dtype: int64

Standardising Column names, and removing duplicates can also be implemented.