<a href="https://colab.research.google.com/github/harkie24/genlink/blob/main/notebooks/Chromosome_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd

In [6]:
genes = pd.read_csv("/content/ensembl_genes.csv")
diseases = pd.read_csv("/content/rare_gene_disease_dataset.csv")

In [7]:
merged = pd.merge(diseases, genes, left_on = 'gene_symbol', right_on = 'gene_symbol', how = 'inner')
merged.head()

,disease,gene_symbol,gene_full_name,ensembl_gene_id,chromosome,start,end,strand,biotype,description
0,Multiple epiphyseal dysplasia-macrocephaly-fac...,KIF7,kinesin family member 7,ENSG00000166813,15,89608789,89663098,-1,protein_coding,kinesin family member 7 [Source:HGNC Symbol;Ac...
1,Brachydactyly-short stature-retinitis pigmento...,CWC27,CWC27 spliceosome associated cyclophilin,ENSG00000153015,5,64766368,65102412,1,protein_coding,CWC27 spliceosome associated cyclophilin [Sour...
2,Aspartylglucosaminuria,AGA,aspartylglucosaminidase,ENSG00000038002,4,177430774,177442444,-1,protein_coding,aspartylglucosaminidase [Source:HGNC Symbol;Ac...
3,Multiple sulfatase deficiency,SUMF1,sulfatase modifying factor 1,ENSG00000144455,3,3700814,4467273,-1,protein_coding,sulfatase modifying factor 1 [Source:HGNC Symb...
4,Beta-mannosidosis,MANBA,mannosidase beta,ENSG00000109323,4,102630770,102760999,-1,protein_coding,mannosidase beta [Source:HGNC Symbol;Acc:HGNC:...

**Chromosome Analysis**

In [8]:
chromosome_counts = (merged['chromosome'].value_counts())
chromosome_counts

chromosome
1     773
2     615
11    547
3     523
17    518
X     457
12    433
6     402
19    364
7     360
5     353
10    339
16    330
4     322
9     312
14    281
8     275
15    262
22    197
20    179
13    159
18    133
MT     86
21     83
Y      18
Name: count, dtype: int64